arm:
  # kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_search_resolution: 0.0025
  # kinematics_solver_timeout: 0.05
  # kinematics_solver_attempts: 5
  # max_cache_size: 100000

  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.02
  # kinematics_solver_attempts: 1

  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
